### ISSUE TITLE
Cannot connect bike to qz app 

### ISSUE THREAD

**Issue by edc3edc3** [cagnulein/QZCompanionNordictrackTreadmill#119] opened 2024-10-31 08:31 UTC
The Bike PROFORM CARBON C7S PF20 BIKE doesn't connect to the app. The qz app says connecting, or it says that it has connected to an applewatch or airpods. (i have tried forgetting these devices and still the qz app says connecting)

Factory reset bike, 
enabled privilege mode and usb debugging. 
qz installation method 1 (log attached)
in the qz app added ip  to bike options - proform/norditrack options - TDF compaion IP
closed app, opened app 
enabled virtual device, virtual device Bluetooth, wahoo direct connect
closed app, opened app 
tiles loaded, says connecting all values 0 
started manual workout, tiles still value 0 
![tiles 0](https://github.com/user-attachments/assets/59da7a3a-6262-442b-9a4d-ff4c433c0090)
[QZ-Companion-log.txt](https://github.com/user-attachments/files/17585130/QZ-Companion-log.txt)
[debug-Thu_Oct_31_18_13_01_2024.txt](https://github.com/user-attachments/files/17585133/debug-Thu_Oct_31_18_13_01_2024.txt)

Devices used, Iphone 15 ios version 18.0.1
PROFORM CARBON C7S PF20 BIKE

**Comment by cagnulein** [comment] 2024-10-31 08:37
hi @edc3edc3 , log checked. it seems that the companion app is not sending anything at all. did you leave the "other" device on the companion? are the bike and the iphone on the same wifi? which wifi router do you have? It seems that it's dropping the broadcast frames from the bike to the iphone

let me know!

**Comment by edc3edc3** [comment] 2024-10-31 08:43
The bike and the phone are on the same network , the router is tp-link AC1200. The "other" device, is that a device separate from the phone and bike? only currently using the phone and bike.

**Comment by cagnulein** [comment] 2024-10-31 08:45
no i mean, in the companion which device do you select in the device selection? you should use "other" as an option.

**Comment by edc3edc3** [comment] 2024-10-31 08:49
Where do i find the device selection sorry.

**Comment by cagnulein** [comment] 2024-10-31 08:51
ok i guess it's the issue :) you have to open the companion app on your bike tablet

**Comment by edc3edc3** [comment] 2024-10-31 08:56
I'm not quite sure what you are referring too when you say "companion". On my iPhone I have the QZ App installed and on the ProForm Bike I have the companion app installed correct? I don't believe in either instance I had a device selection. Any clarification you can provide would be greatly appreciated.

Also i haven't attempted to install or configure zwift as i cannot get the live tiles

**Comment by cagnulein** [comment] 2024-10-31 08:59
Yes i'm talking on the bike. On the bike you have installed the companion through the script from your pc. Now on the bike you have the companion app. It's an app that you have to open to enable the communication with the qz main app on your iphone.
Let me know if you have any other questions

**Comment by edc3edc3** [comment] 2024-10-31 08:59
I found the section you are talking about, and will try that

**Comment by cagnulein** [comment] 2024-10-31 09:02
Ok, let me know.
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 31 ott 2024 alle ore 10:00 edc3edc3 ***@***.***>
ha scritto:

**Comment by edc3edc3** [comment] 2024-10-31 09:07
selected my device as other, allowed app permissions. tiles say 0 and here is the debug 


[debug-Thu_Oct_31_19_04_50_2024.txt](https://github.com/user-attachments/files/17585483/debug-Thu_Oct_31_19_04_50_2024.txt)

**Comment by cagnulein** [comment] 2024-10-31 09:11
ok that's a step forward! now i can see the messages from the companion but they are all empty.
ok let's do this by step a step:

try to select instead of other the c1750 and reboot the bike, if it doesn't work try the same with t75s and also if it doesn't work try this method instead

https://github.com/cagnulein/qdomyos-zwift/issues/1591#issuecomment-1664105559

let me know!

**Comment by edc3edc3** [comment] 2024-10-31 09:27
I have tried 2 different c1750's and t72s, here are the logs. 

I do no have enough time to try the 3rd method at the moment can try that in a couple hours. 
I am no quite sure on those instructions as i am not overly tech savvy, any chance you can simplify that for me? 
Just to clarify i should be using "other" when trying that next method?
[debug-Thu_Oct_31_19_14_58_2024.txt](https://github.com/user-attachments/files/17585670/debug-Thu_Oct_31_19_14_58_2024.txt)
[debug-Thu_Oct_31_19_21_52_2024.txt](https://github.com/user-attachments/files/17585675/debug-Thu_Oct_31_19_21_52_2024.txt)

[debug-Thu_Oct_31_19_17_45_2024.txt](https://github.com/user-attachments/files/17585673/debug-Thu_Oct_31_19_17_45_2024.txt)

**Comment by cagnulein** [comment] 2024-10-31 09:31
> Just to clarify i should be using "other" when trying that next method?

no you have to use the gran tour device as described in the link. you can try to set the gran tour and reboot the bike even without doing the other steps, just to check if it's working

**Comment by edc3edc3** [comment] 2024-10-31 09:40
Quickly tried gran tour and same result

[debug-Thu_Oct_31_19_34_34_2024.txt](https://github.com/user-attachments/files/17585769/debug-Thu_Oct_31_19_34_34_2024.txt)

**Comment by edc3edc3** [comment] 2024-10-31 11:18
Used the apk provided as the install, bike asked for permission  to record screen, said yes, device selected was other. tiles still read 0
[debug-Thu_Oct_31_21_15_29_2024.txt](https://github.com/user-attachments/files/17586983/debug-Thu_Oct_31_21_15_29_2024.txt)

**Comment by cagnulein** [comment] 2024-10-31 11:20
after the first log i can't see anymore the messages from the companion. that's very strange.
are you able to run the adb-debug script while you are doing a quick workout so i can check if the companion is working correctly?

**Comment by edc3edc3** [comment] 2024-10-31 11:26
Ran the adb-debug script while doing a workout, and this is what the output was in the cmd 

![image](https://github.com/user-attachments/assets/fd6509a7-2f3c-4262-94a3-9f1f456c539c)

the log cat file was empty at the end.

**Comment by cagnulein** [comment] 2024-10-31 11:35
reboot the pc and do it again, i guess it was just a glitch of windows (i hope)

**Comment by edc3edc3** [comment] 2024-10-31 11:42
ensured usb debugging was on, restarted windows, this is the cmd output, log cat still empty 
[logcat.txt](https://github.com/user-attachments/files/17587173/logcat.txt)
![image](https://github.com/user-attachments/assets/880638c9-bbb9-4b15-a78f-de4608b5491d)
the script i ran was from the "installpackage" adb-debug.bat

**Comment by cagnulein** [comment] 2024-10-31 11:54
the install batch file is still running? it seems that wifi debugging is not responding anymore

**Comment by edc3edc3** [comment] 2024-10-31 12:05
The install batch file worked when i reinstalled the companion when i used the apk you previously provided. I tried running the install batch file again assuming it would fail because it checks if a version was already installed. But now it is stuck on this. 

![image](https://github.com/user-attachments/assets/70d20bb6-0499-4b53-bd1d-8d1cc8f6c8f6)

**Comment by cagnulein** [comment] 2024-10-31 12:28
yes it is the same error of the adb debug script. question: when you reinstalled the new apk, did you do a factory reset?

**Comment by edc3edc3** [comment] 2024-10-31 12:37
Uninstalled it through the android os I'm happy to do a factory reset and attempt it again in the tomorrow installing the new APK in a factory reset bike. I will upload all debug logs when I can! Appreciate your patience and assistance in the matter.

**Comment by cagnulein** [comment] 2024-10-31 12:52
hah ok so i guess the problem is that once you did the factory reset, the ifit app updated itself after installing the companion, closing the doors for future operations with adb.
i suggest to do a factory reset and inibit the ifit app to update itself. then it could be that also the other methods that we already tried could work

let me know!

**Closed** 2024-11-24 18:32 UTC
Labels: wontfix

**Comment by cagnulein** [comment] 2024-11-24 18:50
@edc3edc3 any news?
