### ISSUE TITLE
Elevation Issue - Mike

### ISSUE THREAD

**Issue by jr128128** [cagnulein/QZCompanionNordictrackTreadmill#70] opened 2023-12-30 16:19 UTC
![Sat12-30-2023@10-16-53 12](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/24399426/a6c29b8c-4ef0-4ada-a7c0-0f5d09da8d7b)

**Comment by cagnulein** [comment] 2023-12-30 16:20
hi, you did great but i need a screenshot of the manual window of ifit :)

**Comment by jr128128** [comment] 2023-12-30 16:24
![Sat12-30-2023@10-23-35 13](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/24399426/bc6061f9-f713-4e0d-bb8d-2078d64ef3cb)

**Comment by cagnulein** [comment] 2023-12-30 16:29
i mean this page

https://private-user-images.githubusercontent.com/154957510/293466814-12c1583f-ed31-4ea5-b840-73fab0f55c63.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NTQwNDIsIm5iZiI6MTcwMzk1Mzc0MiwicGF0aCI6Ii8xNTQ5NTc1MTAvMjkzNDY2ODE0LTEyYzE1ODNmLWVkMzEtNGVhNS1iODQwLTczZmFiMGY1NWM2My5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDIzMTIzMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMzBUMTYyOTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTZlNTEwMjE1ODNkNGQyYzM3YTQ2MWE2M2I2NzAzYzUxOWEyOGE1ZThiNDZlZjI0ZjNhODgyNDdiYjQwYTA5MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CdS_r4mFbfC_7Ky_1HAJuHOObIVOkMZqcLMBzZujp2c

**Comment by cagnulein** [comment] 2023-12-30 16:29
i mean this page https://github.com/cagnulein/qdomyos-zwift/issues/1916#issuecomment-1872544244

**Comment by jr128128** [comment] 2023-12-30 16:38
![Sat12-30-2023@10-32-15 15](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/24399426/ac31de2b-6ff3-4186-91bd-b58169261a14)
![Sat12-30-2023@10-31-02 16](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/24399426/ddbf3d1b-3202-44d1-9dac-becb30b3379c)

**Comment by cagnulein** [comment] 2023-12-30 16:43
thanks i will check this in the next days. as far i can see you have a old/differnt version from the s22i that I already added. Could you please write here the exact device model that you have? so i will add it as a new label in the companion
thanks

**Comment by jr128128** [comment] 2023-12-30 16:47
The model is: NTEX02121.5

**Comment by cagnulein** [comment] 2023-12-31 08:54
I'm doing this right now!

**Comment by cagnulein** [comment] 2023-12-31 09:05
@jr128128 new release for you! https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.23/QZCompanionNordictrackTreadmill.apk

select then your model device in the companion and restart the bike! let me know. do a static test with qz only
Let me know!

**Comment by jr128128** [comment] 2023-12-31 14:03
At some point while pressing the inclination + a few times the bike raised to 5*, but it has not responded to with any kind of consistency.

**Comment by jr128128** [comment] 2023-12-31 14:06
For fun I have been pressing buttons, and it appears that the speed +/- controls the inclination.

**Comment by cagnulein** [comment] 2023-12-31 14:16
mmm did you set the ip in the tdf companion ip? it seems like you are set it on the treadmill settings instead

**Comment by jr128128** [comment] 2023-12-31 14:17
The IP is in the treadmill app. What is the tdf?

**Comment by cagnulein** [comment] 2023-12-31 14:18
show me where you set the ip of your bike in the qz app :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 31 dic 2023 alle 15:17 jr128128 ***@***.***> ha
scritto:

**Comment by jr128128** [comment] 2023-12-31 14:21
![Screenshot_20231231_081913](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/24399426/df0e95cd-c091-42a0-913f-e8fb857234ab)

**Comment by cagnulein** [comment] 2023-12-31 14:22
as i guessed :) 
remove it from there and press ok and set it instead under bike setting, nordictrack bikes, tdf companion io setting and press ok and restart qz

let me know

**Comment by jr128128** [comment] 2023-12-31 14:28
Here?

![Screenshot_20231231_082647](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/24399426/7b813d3e-a52a-4e85-a9fb-13efdf154567)

**Comment by cagnulein** [comment] 2023-12-31 14:30
yes exactly

**Comment by jr128128** [comment] 2023-12-31 14:30
It went to +5 then -10 and is not controllable any longer.

**Comment by cagnulein** [comment] 2023-12-31 14:40
share me a debug log and i will check it, repeating the operation that gave
you this error
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

thanks


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 31 dic 2023 alle 15:30 jr128128 ***@***.***> ha
scritto:

**Comment by jr128128** [comment] 2023-12-31 15:10
[debug-Sun_Dec_31_09_00_46_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13801485/debug-Sun_Dec_31_09_00_46_2023.log)

I think I got it

**Comment by cagnulein** [comment] 2023-12-31 15:18
thanks i will be check it asap

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 31 dic 2023 alle 16:10 jr128128 ***@***.***> ha
scritto:

**Comment by jr128128** [comment] 2023-12-31 15:38
For fun I took it for a ride in zwift. The first incline is always +5. Does it have to do with the top of the slider bar being so close to the #5 inclination on the slider? I have seen it adjust up and down in small increments from there, but the changes do not match the grade in Zwift. Then at some point it gets a -10 input and the inclination stops working all together until I place it back to zero and  then the first increase is +5 again and the cycle repeats.

**Comment by cagnulein** [comment] 2023-12-31 15:46
first i have to check the first log, it should be something simple to fix :) i will have some family days right now.

**Comment by jr128128** [comment] 2023-12-31 15:48
Thanks for the help! I really appreciate it! 

Happy New Year to you and your family!

**Comment by cagnulein** [comment] 2023-12-31 15:56
Happy holidays!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 31 dic 2023 alle ore 16:49 jr128128 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2023-12-31 16:16
> [debug-Sun_Dec_31_09_00_46_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13801485/debug-Sun_Dec_31_09_00_46_2023.log)
> 
> I think I got it

i checked the log but it's a 0 byte file. could you please send it again?

**Comment by jr128128** [comment] 2023-12-31 16:19
[debug-Sun_Dec_31_09_00_46_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13801681/debug-Sun_Dec_31_09_00_46_2023.log)

**Comment by cagnulein** [comment] 2023-12-31 16:21
i can see only partially but I guess I found the issue, hold on

**Comment by cagnulein** [comment] 2023-12-31 16:26
@jr128128 new release https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.24/QZCompanionNordictrackTreadmill.apk

let me know!

**Comment by jr128128** [comment] 2023-12-31 16:26
Will do!

**Comment by jr128128** [comment] 2023-12-31 16:32
It only goes up in increments of 5 or 4.5. It will not reduce the inclination. Need another debug log?

**Comment by cagnulein** [comment] 2023-12-31 16:36
do you mean like 0 then 5 then 10?
yes  a debug log will be useful, there would be something else so

**Comment by jr128128** [comment] 2023-12-31 16:47
[debug-Sun_Dec_31_10_35_08_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13801729/debug-Sun_Dec_31_10_35_08_2023.log)

**Comment by cagnulein** [comment] 2023-12-31 16:57
got the issue it's a stupid , against . issue
On your bike tablet, are you able to change the decimal separator from , to
. ?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 31 dic 2023 alle ore 17:47 jr128128 ***@***.***>
ha scritto:

**Comment by jr128128** [comment] 2023-12-31 16:58
Yes, which one?

**Comment by cagnulein** [comment] 2023-12-31 16:59
change from "," to "."

**Comment by jr128128** [comment] 2023-12-31 17:00
I am unsure of what you need changed.

**Comment by cagnulein** [comment] 2023-12-31 17:02
the decimal separator in the settings of the bike tablet.
let me know if it's not possible. in case i will do another modification in
the companion

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 31 dic 2023 alle ore 18:01 jr128128 ***@***.***>
ha scritto:

**Comment by jr128128** [comment] 2023-12-31 17:04
I am unsure of the location of this

**Comment by cagnulein** [comment] 2023-12-31 17:05
ok let me do the mod in the companion, already did it :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 31 dic 2023 alle ore 18:04 jr128128 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2023-12-31 17:08
ready
https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.25/QZCompanionNordictrackTreadmill.apk
I hope it will be ok

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 31 dic 2023 alle ore 18:05 cagnulein ***@***.***> ha
scritto:

**Comment by jr128128** [comment] 2023-12-31 17:10
Me too! I will let you know!

**Comment by jr128128** [comment] 2023-12-31 17:42
In QZ both the + & - button cause the bike to rise. This is pretty consistent. I do notice it is still moving in 4-5 degree increments. I tried a test in Zwift and the result was the same as from QZ. The first increase is always up and 5*.

Debug below.

[debug-Sun_Dec_31_11_33_29_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13801825/debug-Sun_Dec_31_11_33_29_2023.log)

**Comment by cagnulein** [comment] 2023-12-31 17:44
ok so my patch didn't work.
i will check tomorrow, i turned off the pc now
Have a happy end of year!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 31 dic 2023 alle 18:42 jr128128 ***@***.***> ha
scritto:

**Comment by jr128128** [comment] 2023-12-31 17:45
Have a great one! I owe ya for all the work you are putting in on this.

**Comment by cagnulein** [comment] 2024-01-01 07:51
hi @jr128128 log checked. are you able to collect a debug log from the companion running the [adb-debug.bat](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/blob/master/InstallPackage/adb-debug.bat) script in the install package folder after pressed the inclination plus button on qz? the problem now is in the companion
Let me know!

**Comment by jr128128** [comment] 2024-01-02 22:12
[debug-Tue_Jan_2_16_06_58_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13814277/debug-Tue_Jan_2_16_06_58_2024.log)

Let me know if this is what you needed. Sorry about the delay. I didnt see this message come through.

**Comment by cagnulein** [comment] 2024-01-03 06:00
hi @jr128128 nope this is a log
from the qz main app, i need a debug log from the companion using the batch file mentioned above

**Comment by jr128128** [comment] 2024-01-03 12:59
Would you be kind enough to help me understand the process a little better? I know where the installer file and adb-debug.bat file are on my pc, but I am unsure how to get the companion information instead of the application information. I am at work until 4pm CST today, but will do this as soon as I get home.

**Comment by cagnulein** [comment] 2024-01-03 13:03
ok i will probably be in bed then (italy here) :D

when you run the adb-debug.bat it will create some log file in the same folder. just push them here. you need to run this batch file from a command line like you did in the past

let me know! 

@victorypoint maybe you can help here in case I will be in bed :P

**Comment by victorypoint** [comment] 2024-01-03 13:57
Hi @jr128128. I can try to help. Have you tried running adb-debug.bat yet?

**Comment by jr128128** [comment] 2024-01-03 22:24
I just got home. What is the file you are looking for? Im assuming its going to be on the phone not the pc?

**Comment by jr128128** [comment] 2024-01-03 22:29
[debug-Wed_Jan_3_16_27_16_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13824050/debug-Wed_Jan_3_16_27_16_2024.log)

**Comment by jr128128** [comment] 2024-01-03 22:29
[debug-Wed_Jan_3_16_19_03_2024.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13824053/debug-Wed_Jan_3_16_19_03_2024.log)

**Comment by jr128128** [comment] 2024-01-03 22:29
Those are the two files I pulled off the phone.

**Comment by cagnulein** [comment] 2024-01-04 04:21
@jr128128 nope this is the debug log from qz, you need to run the batch file. did you run it?

**Comment by jr128128** [comment] 2024-01-04 11:15
I ran the debug from the pc with the ip address of the tread mill when prompted. These are the only files I could find on the phones android file. Can you explain in detail what you are looking for and the process to get it?

**Comment by jr128128** [comment] 2024-01-04 11:23
[logcat.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13829277/logcat.log)

**Comment by jr128128** [comment] 2024-01-04 11:24
[logcat.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13829281/logcat.txt)

**Comment by jr128128** [comment] 2024-01-04 11:24
[2024-01-03_logs.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13829286/2024-01-03_logs.txt)

**Comment by jr128128** [comment] 2024-01-04 11:25
[2024-01-03.logs.txt](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13829290/2024-01-03.logs.txt)

**Comment by jr128128** [comment] 2024-01-04 11:25
That is every log file and wolf file I can find with yesterdays date.

**Comment by cagnulein** [comment] 2024-01-04 11:27
ok i will check this later today, thanks!

**Comment by cagnulein** [comment] 2024-01-04 13:22
ok @jr128128 i understood the issue frm your logs, thanks.
But now I need your help to find the solution.
Let me explain:

the problem is about the coordinates of your touchscreen of the bike. It seems that when QZ companion say to move the slider of 0.5, it moves of 5%

in order to understand this, let's try this.

1. put the bike in the manual as usual and put the inclination to 0%
2. open a command shell on your pc as you usually do for the log
3. go into the adb folder as usual
4. now, here type this command ./adb shell input swipe 75 523 75 435 200

This is the command that qz sends to change the incline from 0% to 0.5%.
When you type the command 4. i guess you will see the incline goes to 5%

If so put again the incline manually to 0% and this time try to change the numbers of the swipe command

checking the values, don't change the 75 (that's the X coordinate), the 523 it's the starting point, the 435 is the final point

so maybe you can try a 
./adb shell input swipe 75 563 75 495 200

to check if the behaviour changes.

The scope of this is finding the right number to change of 0.5% the grade.

Can you do this?

Unfortunately you are the only one that can test this since you have the bike :)

let me know!

**Comment by victorypoint** [comment] 2024-01-04 16:09
@cagnulein, here are the pixel equations I came up with based on @jr128128 bike screenshots:

Screen size: 1920 x 1080
Middlex incline - 77
Middlex speed - 1847
BottomY - 803
TopY - 248
incline slider range = -10 - 20 = 30
speed slider range = 1 - 24 = 23

Y delta = 803 - 248 = 559 pixels = 555
Speed-pixels = 555 / 23 = 24.1 pixels / 1 speed
Incline-pixels = 555 / 30 = 18.5 pixels / 1 incline

Speed slider

Speed scale factor - (BottomY - TopY) / speed range = 555 / 23 = 24.1
Step 1: get speed slider position from current speed - speedY = BottomY - round((current speed - 1) * 24.1)
Step 2: set new slider position from new speed - speedY2 = speedY - round((newspeed - current speed) * 24.1)
Round current and target speeds to 1 decimal
The swipe is then - Input swipe 1847 speedY 1847 speedY2

Incline slider

Inclination scale factor - (BottomY - TopY) / incline range = 554 / 30 = 18.5
Step 1: get incline slider position from current incline - inclineY = BottomY - round((current speed - 1) * 18.5)
Step 2: set new slider position from new incline - inclineY2 = inclineY - round((newincline - current incline) * 18.5)
Round current and target incline to 1 decimal
The swipe is then - Input swipe 77 inclineY 77 inclineY2

**Comment by victorypoint** [comment] 2024-01-04 16:11
@cagnulein, sorry speed in this case is actually resistance

**Comment by cagnulein** [comment] 2024-01-04 16:15
@victorypoint since incline is -10% which is the value for the incline on 0% for y? i assumed 532 more or less

From your number there is no a big gap from mine that could explain the @jr128128 issue, do you agree?

**Comment by victorypoint** [comment] 2024-01-04 19:26
@cagnulein, ok assuming the incline slider is initially at -10% :

Step 1: inclineY = 803 - round((-10 - 1) * 18.5) = 803 - -204 = 1007
Step 2: inclineY2 = 1007 - round((0 - -10) * 18.5) = 1007 - -185 = 1192

incline swipe is: Input swipe 77 1007 77 1192

**Comment by victorypoint** [comment] 2024-01-04 19:30
@cagnulein, I really need to verify this swipe. Don't take my word for it yet 🤣

**Comment by cagnulein** [comment] 2024-01-04 19:31
ahahaha no problem anyway i guess it's starting from 0% inclination by
default

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 4 gen 2024 alle 20:30 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment] 2024-01-04 19:46
@cagnulein, OOOPSS! 😂Yah I messed up on the incline equation. It should be:

Step 1: get incline slider position from current incline - inclineY = BottomY - round((current incline + 10) * 18.5)
Step 2: set new slider position from new incline - inclineY2 = inclineY - round((newincline + current incline) * 18.5)
Round current and target incline to 1 decimal

So, assuming the incline slider is initially at -10% :

Step 1: inclineY = 803 - round((-10 +10) * 18.5) = 803 - 0 = 803
Step 2: inclineY2 = 803 - round((0 + -10) * 18.5) = 803 -185 = 618

incline swipe is: Input swipe 77 803 77 618

**Comment by jr128128** [comment] 2024-01-04 22:28
I am finally home. I have no idea where to input the ./adb shell input swipe 75 803 75 618 200

Sorry I need so much help. I'm not a super user by any means.

**Comment by cagnulein** [comment] 2024-01-05 07:19
you have to type it where you start the adb-debug file. same way

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 4 gen 2024 alle 23:28 jr128128 ***@***.***> ha
scritto:

**Comment by victorypoint** [comment] 2024-01-05 14:47
Hi @jr128128. Check Roberto's previous message at https://github.com/cagnulein/QZCompanionNordictrackTreadmill/issues/70#issuecomment-1877088733. You will need to go to the Windows command prompt and inside the folder where you have the QZ Companion. Let me know if you need any help from there.

**Comment by jr128128** [comment] 2024-01-05 14:55
I have been running the adbdebug straight from the installer files in the file explorer. I am not sure how to navigate to the adb from a blank CMD prompt.

**Comment by cagnulein** [comment] 2024-01-05 15:05
@jr128128 with the cd function

for example

cd \

put you to c:\

cd adb

put you into the

c:\adb folder 

and so on

with the dir command you can see where you are and which files are in

**Comment by jr128128** [comment] 2024-01-05 16:10
I am still not certain what you mean. Any resources to better understand this?

**Comment by cagnulein** [comment] 2024-01-05 16:13
maybe this helps https://learn.microsoft.com/it-it/windows-server/administration/windows-commands/cd ?

**Comment by jr128128** [comment] 2024-01-05 16:26
Once I am there how do I connect to the machine to send the command or am I over thinking this?

**Comment by cagnulein** [comment] 2024-01-05 16:28
just do first

./adb connect ipofyourtreadmilll

**Comment by victorypoint** [comment] 2024-01-05 16:54
@jr128128, attached is a batch script to test the swipe on your bike tablet. Download the attached file and unzip it in the same folder as your qz companion. Next, follow Robertos previous instructions to run your bike in manual workout mode, 0% incline, and make sure the onscreen sliders are visible. Next, double-click the adb-swipe.bat file, enter your machines IP address when prompted, and let us know what happens - does your incline slider move?

[adb-swipe.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13844585/adb-swipe.zip)

**Comment by victorypoint** [comment] 2024-01-05 16:55
@cagnulein, FYI, in the batch script, I'm moving the incline slider from 0 to 5%:

Step 1: inclineY = 803 - round((0 +10) * 18.5) = 803 - 185 = 618
Step 2: inclineY2 = 618 - round((5 - -10) * 18.5) = 618 - 278 = 340

incline swipe is: adb shell input swipe 77 618 77 340 200

**Comment by victorypoint** [comment] 2024-01-05 17:02
@cagnulein, ok sure. So do you want to try 0 to 0.5% ? I can modify the .bat for this and add several more swipes to test. We should wait to see if the 0 to 5% works first from @jr128128.

**Comment by cagnulein** [comment] 2024-01-05 17:06
yes just wait his feedback.
anyway i guess we should also check smaller changes

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 5 gen 2024 alle ore 18:02 Al Udell ***@***.***>
ha scritto:

**Comment by jr128128** [comment] 2024-01-05 17:06
I would imagine you would like to see the debug after I run the adb swipe test?

**Comment by cagnulein** [comment] 2024-01-05 17:07
nope, just test it @jr128128

**Comment by jr128128** [comment] 2024-01-05 17:13
10-4

**Comment by cagnulein** [comment] 2024-01-05 17:17
sorry? what do you mean?

**Comment by jr128128** [comment] 2024-01-05 17:20
I will try it as soon as I get home. 

10-4 is common American slang for received and understood. I believe its origin is from CB  (citizen band) radio.

**Comment by jr128128** [comment] 2024-01-05 21:19
I ran the batch file and there was no inclination change.

**Comment by jr128128** [comment] 2024-01-05 21:30
Guys. Results of some trial and error below

77 618 77 340 200 - raised to 14.5

77 618 77 100 200 - raised to 20

77 618 77 500 200 - raised to 6.5

77 618 77 600 200 - raised 1

77 618 77 610 200 - raised .5

**Comment by jr128128** [comment] 2024-01-05 21:35
With 77 618 77 610 200 I can raise the machine incrementally by .5 up over and over again without resetting the machine to zero.

**Comment by victorypoint** [comment] 2024-01-05 21:38
@jr128128, this is excellent. Good work. Can you confirm where this puts the slider?

77 618 77 618 200

**Comment by jr128128** [comment] 2024-01-05 21:40
It took it from 0 to .5, .5 to 1, 1 to 1.5, 1.5 to 2, etc

**Comment by victorypoint** [comment] 2024-01-05 21:40
@jr128128, you can also turn this treadmill option on to see the start and end points of the wipes:

Settings > Developer Options > Input > Pointer Location

**Comment by jr128128** [comment] 2024-01-05 21:40
sorry. I will test 618 to 618

**Comment by jr128128** [comment] 2024-01-05 21:42
618 to 618 caused no change

**Comment by victorypoint** [comment] 2024-01-05 21:43
> 618 to 618 caused no change

Did the incline go to 0% ?

**Comment by jr128128** [comment] 2024-01-05 21:47
No, but adb shell input swipe 77 618 77 626 200 did make it go to zero and operates in .5 steps down consistently.

**Comment by jr128128** [comment] 2024-01-05 21:51
and 610 increased it back incrementally by .5 to zero when run a few times. I think 610 is up by .5 and 626 is down by .5. Is that what we are looking for?

**Comment by victorypoint** [comment] 2024-01-05 22:31
@jr128128, can you provide another screenshot of your treadmill manual workout screen with the sliders, but with the incline slider at a very high or low position so I can clearly see the 0% box?

**Comment by jr128128** [comment] 2024-01-05 23:05
![Fri01-05-2024@17-04-06 48](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/24399426/ca3720fe-0269-411e-8922-68b6e553a7d0)

here is the screen shot. Im just about to start the testing on the incremental moves.

**Comment by victorypoint** [comment] 2024-01-05 23:59
@jr128128, cool thanks! So calculating from your screenshot I get:

swipe 77 618 77 803 200 - goes from 0 to -10% (assuming start incline is at 0%)
swipe 77 618 77 248 200 - goes from 0 to 20% (assuming start incline is at 0%)

**Comment by jr128128** [comment] 2024-01-06 00:01
I am working on mapping the correct pixel values manually by .5 up and down. I have the up done. Just starting the down. I will report back soon.

**Comment by jr128128** [comment] 2024-01-06 00:03
I have adjusted the nominal to 610 based on trial and error. There are a few that only move by 5 instead of 10 but I will show you.

**Comment by jr128128** [comment] 2024-01-06 00:22
Here are the values

Up from 0
77 610 77 600 200 = 0.5

77 610 77 590 200 = 1.0

77 610 77 580 200 = 1.5

77 610 77 570 200 = 2.0

77 610 77 560 200 = 2.5

77 610 77 550 200 = 3.0

77 610 77 540 200 = 3.5

77 610 77 530 200 = 4.0

77 610 77 525 200 = 4.5

77 610 77 520 200 = 5.0

77 610 77 510 200 = 5.5

77 610 77 500 200 = 6.0

77 610 77 490 200 = 6.5

77 610 77 480 200 = 7.0

77 610 77 470 200 = 7.5

77 610 77 460 200 = 8.0

77 610 77 450 200 = 8.5

77 610 77 440 200 = 9.0

77 610 77 430 200 = 9.5

77 610 77 420 200 = 10.0

77 610 77 410 200 = 10.5

77 610 77 400 200 = 11.0

77 610 77 390 200 = 11.5

77 610 77 380 200 = 12.0

77 610 77 370 200 = 12.5

77 610 77 365 200 = 13.0

77 610 77 360 200 = 13.5

77 610 77 350 200 = 14.0

77 610 77 340 200 = 14.5

77 610 77 330 200 = 15.0

77 610 77 320 200 = 15.5

77 610 77 305 200 = 16.0

77 610 77 300 200 = 16.5

77 610 77 290 200 = 17.0

77 610 77 280 200 = 17.5

77 610 77 270 200 = 18.0

77 610 77 260 200 = 18.5

77 610 77 250 200 = 19.0

77 610 77 240 200 = 19.5

77 610 77 230 200 = 20.0




Down
77 610 77 620 200 = -0.5

77 610 77 630 200 = -1.0

77 610 77 640 200 = -1.5

77 610 77 650 200 = -2.0

77 610 77 660 200 = -2.5

77 610 77 670 200 = -3.0

77 610 77 680 200 = -3.5

77 610 77 690 200 = -4.0

77 610 77 695 200 = -4.5

77 610 77 700 200 = -5.0

77 610 77 710 200 = -5.5

77 610 77 720 200 = -6.0 

77 610 77 730 200 = -6.5

77 610 77 740 200 = -7.0

77 610 77 750 200 = -7.5

77 610 77 760 200 = -8.0

77 610 77 770 200 = -8.5

77 610 77 780 200 = -9.0

77 610 77 790 200 = -9.5

77 610 77 800 200 = -10.0

**Comment by jr128128** [comment] 2024-01-06 00:23
I dont have it perfect because there are a few 5 steps instead of all being 10's but, I am assuming you can take the total range and divide by the number of ups & downs and get an idea of the steps.

**Comment by victorypoint** [comment] 2024-01-06 00:47
@jr128128, this is great stuff! Thanks very much. So converting to equations I get:

Current incline in y pixels: inclineY = 800 - round((current incline +10) * 19.0)
New incline in y pixels: inclineY2 = inclineY - round((new incline - current incline) * 19.0)
Swipe is: 77 inclineY 77 inclineY2 200

For example based on @jr128128's excellent work above:

Start at 0% go to -10%
inclineY = 800 - round((0 + 10) * 19.0) = 800 - 190 = 610
inclineY2 = 610 - round(-10 - 0) * 19.0) = 610 - -190 = 800
Swipe is: 77 610 77 800 200

Start at 0% go to 20%
inclineY = 800 - round((0 + 10) * 19.0) = 800 - 190 = 610
inclineY2 = 610 - round(20 - 0) * 19.0) = 610 - 380 = 230
Swipe is: 77 610 77 230 200

Guys, can you confirm these equations? They should work for any start incline and end incline.

**Comment by cagnulein** [comment] 2024-01-06 06:40
wow what an amazing teamwork here! @jr128128 could you please try to validate the equation of @victorypoint so I can add them in the companion? or you would like to go directly in the companion? let me know!

**Comment by jr128128** [comment] 2024-01-06 06:51
If his equation is right let's give it a shot. I'm confident in the data I provided.

**Comment by cagnulein** [comment] 2024-01-06 06:53
ok i will add this later today or tomorrow. i'm traveling today

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 6 gen 2024 alle 07:51 jr128128 ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-01-07 08:08
done @jr128128 let me know https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.3.26/QZCompanionNordictrackTreadmill.apk

**Comment by jr128128** [comment] 2024-01-07 14:09
All seems to be as it should! The app controls the inclination by .5 steps up and down. I took a quick test ride in Zwift and the machine is reacting both up and down as the terrain changes. I think you did it! Thank you very much!

**Comment by cagnulein** [comment] 2024-01-07 14:19
amazing! great job guys! i will leave this open in case you need anything
else!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 15:10 jr128128 ***@***.***> ha
scritto:

**Comment by victorypoint** [comment] 2024-01-07 14:25
@jr128128 That's great! @cagnulein did you end up using the equations or the lookup table?

**Comment by cagnulein** [comment] 2024-01-07 14:34
your equation :)

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 7 gen 2024 alle 15:25 Al Udell ***@***.***> ha
scritto:

**Comment by jr128128** [comment] 2024-01-11 18:37
I have had the chance to use this now. It is awesome! I have a few minor questions. 

1. When Zwift changes grade by 1% the elevation on the s22i changes by .5. Is that intended or is there a setting I can play with to increase the amount of movement to better match the grade like a 1:1 ratio?

2. The reaction of the bike is not super fast. Sometimes I am riding up hill with negative values and down hill with positive values. Is there something I can to do speed up the reaction time of the QZ touch signal?

3. Do you know why the QZ app shuts off after riding a while (it happened last night somewhere between 60-90mins)? I can reconnect it to Zwift but that isn't ideal when you are all sweaty.

4. I have the app set to show the QZ icon on the phone when running, but it isn't showing up anymore. Is there a way to fix this?

I am using Zwift & QZ from my Samsung S20+ and I am casting to a TV with the Samsung cast app to a fire stick type device.

**Comment by cagnulein** [comment] 2024-01-11 18:44
1. set the zwift difficulty to 100 in zwift. usually it's 50 by default
2. check the target incline tiles, you have to understand where is the
delay: if from zwift to qz or qz to the bike. i believe the second, if so
there isn't so much to do unfortunately
3. android killed it looking for RAM. android notification is enabled on qz?
4. you mean the notification icon? android notification icon setting in the
experimental settings

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 11 gen 2024 alle 19:37 jr128128 ***@***.***> ha
scritto:

**Closed** 2024-02-03 02:13 UTC
Labels: wontfix

**Comment by cagnulein** [comment] 2024-02-03 05:31
@jr128128 are we ok with this?
