### ISSUE TITLE
Old Treadmill/Android 2 compatibility

### ISSUE THREAD

**Issue by pmckinney4** [cagnulein/QZCompanionNordictrackTreadmill#62] opened 2023-10-22 01:04 UTC
Trying to figure out if I can get the companion app installed on my old treadmill.  It is an EPIC A35T (Made by ICON Fitness) around 2013.  It is running iFit 2.18.8 (rolled back from the version of iFit that disabled wifi on the treadmill).   The OS is Android 2.2.  

I am able to connect it via USB.  I modified the batch file to run the install file without connecting via wifi so it just installs over USB.   

No worries if you can't, I realize it is a 10 year old treadmill.  Just trying to figure out if I can tie it to the Peloton App and breathe a little more life into the old technology.  I attached a zip file that has a folder of logs from the treadmill, a log of the attempted install, and the batch file I modified.  Thanks!

[QZ-Companion-log.zip](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13062127/QZ-Companion-log.zip)

**Comment by cagnulein** [comment] 2023-10-22 05:14
Ok, I'll take a look ASAP!

Il giorno dom 22 ott 2023 alle 03:04 pmckinney4 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2023-10-22 05:58
@pmckinney4 I have a great news! You can already use it without the companion.
In QZ, proform/nordictrack treadmill settings, set the ip of your treadmill in the setting called "Proform IP:" and restart QZ

Let me know!

**Comment by pmckinney4** [comment] 2023-10-22 13:50
Yes, it does connect and show the stats.  That is pretty amazing
considering the age of the tech.  I will need to spend some time adjusting
tiles, but the basics seem to be working.

Does this type of connection allow Peloton to control the speed/incline of
the treadmill or is it just going to receive the data from the treadmill
and I will have to manually adjust?

Thanks so much!

Pat

**Comment by cagnulein** [comment] 2023-10-22 13:54
great! yes we should be possible to control incline and speed for peloton!
give it a try!

Il giorno dom 22 ott 2023 alle 15:50 pmckinney4 ***@***.***>
ha scritto:

**Comment by pmckinney4** [comment] 2023-10-30 00:54
Hello,

I finally had time to test with Peloton.   I was able to get auto-speed
working with no issue.  The auto-incline is not working.

I tested manually adjusting the incline with the incline tile in QZ.  It
raises the incline .5%.  It physically raises the treadmill and shows the
adjustment on the treadmill.  It does not indicate a change of incline on
the tile.  After pressing the raise button the first time on the tile, it
will not respond.   I think I have tried most of the
Proform/Norditrack models of treadmill and the get the same result with
each one.

I attached a debug log.

Honestly, I am happy the speed is working, if you can't figure out the
incline, it is OK.  I just thought I would ask in case it is a simple
setting change that you see.

Thanks!

Pat

**Comment by cagnulein** [comment] 2023-10-30 04:19
hi @pmckinney4 i don't see the debug log. you have to attach it from GitHub directly. thanks

**Comment by pmckinney4** [comment] 2023-10-30 12:12
Sorry about that.   I did just reply with it attached to an email.  I attached it here.
[debug-Sun_Oct_29_20_08_23_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13204971/debug-Sun_Oct_29_20_08_23_2023.log)

**Comment by cagnulein** [comment] 2023-10-30 13:31
hi @pmckinney4 I don't see any peloton workout here. Am I missing something or you uploaded the wrong file? Let me know

**Comment by pmckinney4** [comment] 2023-10-30 13:37
Sorry,  this one isn't from a peloton workout.  I can pull one tied to a
Peloton workout tonight.

For this one, I just started the treadmill in manual mode and then tried
raising the incline with the tile in QZ.  It raised it .5%.  It did not
show that it raised it at all in QZ.  It did show it raised on the
treadmill(in manual workout mode).   I tried hitting the + button on the QZ
tile again and it would not respond after that first attempt to raise the
incline.  I pulled this log file since the treadmill would not respond to
QZ in manual mode after the first call to raise the incline.

**Comment by cagnulein** [comment] 2023-10-30 13:41
@pmckinney4 I can't see the debug log, you have to attach from github directly ;)

**Comment by pmckinney4** [comment] 2023-10-30 23:08
OK, I started a Peloton workout that had incline changes.   I stopped it after the first incline change and there was no response from the treadmill.   Speed changes worked as they should.
[debug-Mon_Oct_30_18_59_12_2023.log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13210469/debug-Mon_Oct_30_18_59_12_2023.log)

**Comment by cagnulein** [comment] 2023-10-31 08:01
@pmckinney4 when you stop it you'are also stopping the peloton workout, that's why you see this :) so it's not a bug but it's a feature :) in that case you have also to stop the peloton workout in the peloton app, wait 30-60 seconds and start a new workout in the peloton app and then you will see a new popup on qz
Let me know if it's not clear

**Comment by pmckinney4** [comment] 2023-10-31 12:30
I apologize, but I am not following what you are saying.  The auto-speed is
working perfectly, the auto incline is not working.   I stopped the workout
after a couple of rounds of speed and incline changes just to get the log.
I didn't want to let it run through the whole workout without it working,
so I stopped it.

If I leave Peloton out of it and just use QZ with manual mode on the
treadmill, I can control speed with the speed tile in QZ.   I try to
control the incline with the incline tile in QZ and it will increase the
incline by .5% one time, but then it will no longer respond to QZ.   That
is the first log I had uploaded without QZ.

If we cannot get auto-incline working with this old treadmill, it is fine.
I understand that it is a 10 year old treadmill.  I am happy the speed
portion works.  I appreciate your efforts!

Pat

**Comment by cagnulein** [comment] 2023-10-31 13:17
ok now I got the issue. The treadmill reacts only to the first inclination request, I guess we need to do something after the first inclination. I will think about it

**Comment by cagnulein** [comment] 2023-10-31 14:18
fixed! it will be in the 2.16.22! I'm building it now, let me know if you can try already in the CI here https://github.com/cagnulein/qdomyos-zwift/actions/runs/6707821411 (when the build will finish you will see the android and windows trial version of QZ 2.16.22, in the next days I will upload it as well on the play store)

**Comment by pmckinney4** [comment] 2023-11-01 00:34
Good news.  I installed the version linked above on the Fire tablet that I
am using.   I tested with the treadmill in manual mode. I can use the tile
in QZ to raise and lower the incline!

I am unable to test with the Peloton app.  2.16.22  is not accepting my
Peloton password.  Is it possible something changed in this trial version
that won't let it link with Peloton?  I just logged in on my Android phone
running 2.16.20 with no issues.  Went back to the Fire tablet running
2.16.22 and tried again, and it still won't work.  It was working on the
tablet with the old version before I removed it and manually installed
2.16.22.

**Comment by pmckinney4** [comment] 2023-11-01 00:39
Sorry, the version I just downloaded to the fire tablet is .21, not .22.

**Comment by cagnulein** [comment] 2023-11-01 05:03
yes there is something on the trial that doesn't like to peloton server.
anyway good news so as soon as google review the new one you will have the
fix too!

Il giorno mer 1 nov 2023 alle 01:39 pmckinney4 ***@***.***>
ha scritto:

**Comment by pmckinney4** [comment] 2023-11-06 00:28
I downloaded the latest version through the play store.   The tile on QZ
can now control the incline.   The app is connected to Peloton.  The speed
changes with the app.   The target incline from Peloton is desiplay on QZ,
however QZ is not changing the incline.   Unfortunately, I didn't realize
the new version I downloaded disabled the logging, so I did not pull a
log.   I'll try to pull one in the next day or two.  Just wanted to let you
know that it is partially working with the new version of the app.

Thanks!

Pat

**Comment by cagnulein** [comment] 2023-11-06 04:36
ok let me know!

Il giorno lun 6 nov 2023 alle 01:28 pmckinney4 ***@***.***>
ha scritto:

**Comment by pmckinney4** [comment] 2023-11-12 00:05
I ran a Peloton workout.   Speed changes worked.   Incline did not change at all.   Incline can be adjusted using the incline tile on QZ, so the app can talk to the treadmill.      I attached the debug file.   I also attached a picture.   The treadmill is registering 3.9mph, but it is only showing 3.5 on QZ.  

This is an EPIC A35T made by iCon fitness about 10 years ago.  I am not sure if there would be a better model for me to select in QZ that my give me better results.
[debug-Sat_Nov_11_10_28_07_2023[1].log](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/files/13326808/debug-Sat_Nov_11_10_28_07_2023.1.log)
![QZ MPH](https://github.com/cagnulein/QZCompanionNordictrackTreadmill/assets/33156038/b7c63a47-cf14-4941-beab-8bd2920e062e)

**Comment by cagnulein** [comment] 2023-11-12 17:29
i guess the issue is that with peloton qz is trying to change at the same
time inclination and speed, this will lead into a null action to the
treadmill.
I will try to separate the event.
You can validate my ipotesis pressing both plus buttons of speed and
incline at the same time, i guess it will not work.
Let me know!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno dom 12 nov 2023 alle ore 01:05 pmckinney4 <
***@***.***> ha scritto:

**Comment by pmckinney4** [comment] 2023-11-12 23:51
I tested.  You are correct, it will not take both commands at the same time.  It works fine to only do one at a time.

**Comment by cagnulein** [comment] 2023-11-13 04:30
perfect, i will add the patch in the next days!

we are near!

Il giorno lun 13 nov 2023 alle 00:51 pmckinney4 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2023-11-13 13:54
done! @pmckinney4 are you on android or ios with qz?

**Comment by pmckinney4** [comment] 2023-11-14 02:21
Android, thanks!

**Comment by cagnulein** [comment] 2023-11-14 04:40
perfect, give it a try to the demo just to check that the issue is fixed
https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/android-debug.apk

google version is updating in a couple of days

Il giorno mar 14 nov 2023 alle 03:21 pmckinney4 ***@***.***>
ha scritto:

**Comment by pmckinney4** [comment] 2023-11-22 02:13
I finally had time to install and test.   It appears to be working to press
the speed and incline buttons on QZ at the same time.   I can't test
with Peloton as the test version won't authenticate with Peloton correctly.

**Comment by cagnulein** [comment] 2023-11-22 05:17
perfect i will push to the play store asap!

Il giorno mer 22 nov 2023 alle 03:13 pmckinney4 ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2023-11-23 15:11
i fixed also the peloton login issue with this one https://github.com/cagnulein/qdomyos-zwift/actions/runs/6971450470

**Closed** 2023-12-15 23:37 UTC
Labels: wontfix
