### ISSUE TITLE
iFit Beta Equipment Software Breaks QZCompanion

### ISSUE THREAD

**Issue by keatontaylor** [cagnulein/QZCompanionNordictrackTreadmill#103] opened 2024-08-01 21:37 UTC
This is just a PSA the beta version of the latest software for the nordictrack hardware appears to no longer write to the wolflogs directory. Thus completely breaks fetching the stats from the bike via that file.

**Comment by keatontaylor** [comment] 2024-08-01 21:46
![IMG_5335](https://github.com/user-attachments/assets/00792f49-625f-40bc-865b-6f3731a3fd52)
![IMG_5334](https://github.com/user-attachments/assets/ac254730-4f87-44c2-bcb2-40b38243f152)

**Comment by cagnulein** [comment] 2024-08-02 06:40
hi @keatontaylor yes i'm aware of this. I guess I should go with some OCR from the ifit app. What do you think @victorypoint  ?

**Comment by cagnulein** [comment] 2024-08-02 06:40
@keatontaylor are you able to leave the beta right?

**Comment by keatontaylor** [comment] 2024-08-02 14:05
@cagnulein I was able to unenroll in the beta program which immediately reboots the equipment and loads the older version of the iFit software. Everything is fully functional again. 

I did spend some time looking for a new file location for the bike status logs. Unfortunately, it appears that the .wolflogs for each day are still created, but it is just an empty file. So I don't think that the new software has debug/trace logging turned off.

**Comment by cagnulein** [comment] 2024-08-02 15:32
Ok this weekend I will play with OCR thing if you are available to test it.
What do you think?

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 ago 2024 alle ore 16:06 Keaton Taylor <
***@***.***> ha scritto:

**Comment by keatontaylor** [comment] 2024-08-02 17:15
Unfortunately I don't see a way to quickly go back to the upgraded app version(s) after un-enrolling.

**Comment by cagnulein** [comment] 2024-08-02 17:24
ok anyway i will put in on the list since i guess more users will use the beta in the future

**Comment by keatontaylor** [comment] 2024-08-02 17:57
Has there been any work in trying to fetch the data from the USB interface similar to how the iFit apps do it? I'd be curious if that might be a more reliable approach if it is something that could fairly easily be reverse engineered.

**Comment by cagnulein** [comment] 2024-08-02 17:59
In order to do so I need someone with the treadmill to make some
experiments :)
I don't have an ifit device :)
Anyway ocr will work just fine I guess

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno ven 2 ago 2024 alle 19:58 Keaton Taylor ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2024-08-07 13:18
[app-debug.apk.zip](https://github.com/user-attachments/files/16529127/app-debug.apk.zip)
@victorypoint apk for OCR, it's just stream in the logcat what it sees. If we can see all the field in the manual workout windows we are good to go!

**Comment by victorypoint** [comment] 2024-08-07 14:40
@cagnulein, full logcat when Companion screen stays open (however no OCR recording prompt appears).
[logcat.zip](https://github.com/user-attachments/files/16530253/logcat.zip)

**Comment by cagnulein** [comment] 2024-08-07 15:02
[app-debug.apk.zip](https://github.com/user-attachments/files/16530508/app-debug.apk.zip)
new one @victorypoint without the alarm to avoid the crash

**Comment by victorypoint** [comment] 2024-08-07 15:22
@cagnulein, new logcats from new apk testing...
[adb scripts.zip](https://github.com/user-attachments/files/16530707/adb.scripts.zip)

**Comment by victorypoint** [comment] 2024-08-07 15:27
@cagnulein, after some fiddling I got the companion prompt to appear and start recording. Logcats show more OCR messages now..
[adb scripts.zip](https://github.com/user-attachments/files/16530780/adb.scripts.zip)

**Comment by cagnulein** [comment] 2024-08-07 15:29
what a relief! so there is hope!

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno mer 7 ago 2024 alle ore 17:28 Al Udell ***@***.***>
ha scritto:

**Comment by cagnulein** [comment] 2024-08-07 16:25
@victorypoint new one. here i'm trying to send the incline and the speed to qz on the other side with the same method as before. Let's see how it goes, probably we need several version to adjust everything. Thanks

https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10288035241/artifacts/1786555345

**Comment by victorypoint** [comment] 2024-08-07 23:42
@cagnulein, here is the logs for the new apk.
[logcats.zip](https://github.com/user-attachments/files/16535699/logcats.zip)

**Comment by cagnulein** [comment] 2024-08-08 07:17
@victorypoint https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10297587613/artifacts/1789131707 
I guess this would be the one!

**Comment by victorypoint** [comment] 2024-08-08 16:23
@cagnulein, logs attached for new apk.
[logcats.zip](https://github.com/user-attachments/files/16550872/logcats.zip)

**Comment by victorypoint** [comment] 2024-08-08 16:58
@cagnulein, not yet. Do I keep all QZ settings the same as before?

**Comment by victorypoint** [comment] 2024-08-08 17:06
@cagnulein, no metrics in QZ unfortunately. Exact same setup as before for QZ.

**Comment by cagnulein** [comment] 2024-08-08 17:09
could you please upload log on QZ app? I would like to see if you are
receiving something on the UDP socket. I don't remember if you were using
all the ADB On your set up
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 8 ago 2024 alle 19:06 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment] 2024-08-08 17:11
@cagnulein, here it is
[debug-Thu_Aug_8_14_08_58_2024.log](https://github.com/user-attachments/files/16551327/debug-Thu_Aug_8_14_08_58_2024.log)

**Comment by cagnulein** [comment] 2024-08-08 17:14
Thanks, I'll check it out. I'm currently running outside now


Il giorno gio 8 ago 2024 alle 19:11 Al Udell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-08-08 18:44
good news I can see everything @victorypoint ! the problem/feature is that with your version, we did everything through adb, but since now the log is not available anymore we have to revert back to the UDP socket. Maybe I can put this under the adb setting that it's already available. I will build a new one for you. Finger crossed!

**Comment by victorypoint** [comment] 2024-08-08 19:47
> good news I can see everything @victorypoint ! the problem/feature is that with your version, we did everything through adb, but since now the log is not available anymore we have to revert back to the UDP socket. Maybe I can put this under the adb setting that it's already available. I will build a new one for you. Finger crossed!

@cagnulein, okay sounds good. I'm using the companion that is compatible with QZ Windows and AI.Server for OCR with Zwift and ADB control of TM speed and incline. I can't recall which build it is.

**Comment by cagnulein** [comment] 2024-08-08 19:59
@victorypoint fixed https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10308626311/artifacts/1792191118

I forgot to add the changed grade and changed speed tag in the udp frames, that's why qz was discarding it :)
give it a go when you have time :P

**Comment by cagnulein** [comment] 2024-08-08 20:52
Good news :)
i will investigate on both issues.
thanks!

Il giorno giovedì 8 agosto 2024, Al Udell ***@***.***> ha
scritto:
> @cagnulein, good! It works! Just a few quick testing notes:
>
> OCR inaccuracies - I changed to various speeds and QZ displayed incorrect
values - e.g. 4.8 on TM was 4.3 in QZ
> time between speed change on TM to QZ display was about 8 second delay
per change
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.<
https://ci3.googleusercontent.com/meips/ADKq_NYfnl4ODAHPGpBONa2z5nYLJeaWS5L5zJAXq3qFOWdp-4_8D3v86k0OJxK9p695AKQrGReCNc3duwHRLFCuN6qLqn27ppIOFq8oO1mxbg-78OmocFl6Cuxo4SIkqizHuTt1LZadnKFJga0S85wtCEcC5S3seuAuz1yH8BbBXa4ZVjVh4DuX5Cxayk5RGPJbHgJCbGeEDK3ty6esnEu6WKpVjK0rET_2J0F5Y0aZ2aF3yMJhknl3kws=s0-d-e1-ft#https://github.com/notifications/beacon/AAALYWDNYWDNESNE5TVKRGTZQPKORA5CNFSM6AAAAABL3L5J6GWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTUHWKGHG.gif>Message
ID: <cagnulein/QZCompanionNordictrackTreadmill/issues/103/
***@***.***>

-- 
Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud

**Comment by cagnulein** [comment] 2024-08-09 06:23
hi @victorypoint checked the 2 things:
- for the precision of the OCR: is it possible to change the DPI or the FONT SIZE on the treadmill settings? This could be probably the easiest solutions
- for the delay i guess I can simple do the ocr only on the bottom part of the display, this should be speed up the process a lot

**Comment by cagnulein** [comment] 2024-08-09 06:29
for my reference 
![image](https://github.com/user-attachments/assets/608585dc-3284-47ec-9992-8e818587c209)

**Comment by cagnulein** [comment] 2024-08-09 07:00
@victorypoint https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10314880819/artifacts/1793804471
i used only the last 100px of the image. it should be 10x faster now theorically, so let's see if the approach is correct

**Comment by victorypoint** [comment] 2024-08-09 12:21
@cagnulein, thanks for this. I'll retest soon. Can you limit the OCR to the specific boxed areas where speed and incline values display rather than larger areas of the image? So for example, using PaddleOCR the boxes are defined as:

{'confidence': 0.9965367317199707, 'label': '15.0', 'x_min': 402, 'y_min': 1014, 'x_max': 468, 'y_max': 1048}
{'confidence': 0.9980539679527283, 'label': '4.8', 'x_min': 1274, 'y_min': 1018, 'x_max': 1324, 'y_max': 1046}

**Comment by victorypoint** [comment] 2024-08-09 16:31
@cagnulein, a bit of a problem this time with the new apk. Most of the speed changes were not transmitted to QZ. Looking at the logs it looks like the OCR may have missed many of the changes.
[logs.zip](https://github.com/user-attachments/files/16564418/logs.zip)

**Comment by cagnulein** [comment] 2024-08-09 16:32
Ok, I'll check it out.
i will try to simulate on my own

Il giorno ven 9 ago 2024 alle 18:31 Al Udell ***@***.***> ha
scritto:

**Comment by victorypoint** [comment] 2024-08-09 16:41
@cagnulein, here's a logcat while I made speed and incline changes about 5 seconds apart. It looks like the OCR is picking up the values but the QZ 'changed kph' and 'changed grade' messages don't reflect all the changes.
[stream-logcat.zip](https://github.com/user-attachments/files/16564509/stream-logcat.zip)

**Comment by cagnulein** [comment] 2024-08-09 16:41
@victorypoint here i can see 1.6 , 6.4 and 8.0 speed
Did you change any other speed? the coordinates seems fine because it can get it

**Comment by cagnulein** [comment] 2024-08-09 16:43
got the issue! it's a simple lowercase, uppercase issue!

**Comment by victorypoint** [comment] 2024-08-09 16:44
> @cagnulein, here's a logcat while I made speed and incline changes about 5 seconds apart. It looks like the OCR is picking up the values but the QZ 'changed kph' and 'changed grade' messages don't reflect all the changes. [stream-logcat.zip](https://github.com/user-attachments/files/16564509/stream-logcat.zip)

Logcat shows "OCRlines: 5" with all the correct speed changes, but " QZ:Service: Changed KPH" messages don't show same metrics
OCRlines: 5

**Comment by cagnulein** [comment] 2024-08-09 16:46
fixed @victorypoint https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10322696079/artifacts/1795843291

**Comment by victorypoint** [comment] 2024-08-09 17:03
@cagnulein, good! All speed and incline changes were transmitted to QZ with no misses. Speed changes were delayed from 4-8 seconds while all incline changes delayed consistently by 4 seconds. FYI - When TM is paused (speed 0), note that the following screen is shown:
![2024-08-09@14-00-44 59](https://github.com/user-attachments/assets/4a3fb399-d06f-43cf-9404-29d75a53beb3)

**Comment by cagnulein** [comment] 2024-08-09 17:06
hah ok so i can handle the text "resume".
about the performance i have to investigate if it's something about grabbing the new images or the processing

**Comment by cagnulein** [comment] 2024-08-09 17:52
@victorypoint last build for today (from tomorrow I will be in vacation, but I will take my Mac with me ;): I just checked the timing on my old android 8 tablet and the whole process, ocr and send it's about 500ms, so 4 seconds sounds an eternity to me.
I added in this build some print on the companion to understand how the OCR process is long. If you can collect the log i can compare between my tablet to understand where is the issue https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10323480282/artifacts/1796052301

Thanks

**Comment by victorypoint** [comment] 2024-08-09 18:20
@cagnulein, with this apk there appears to be no OCR process working. See attached logcat. I confirmed that recording has been enabled on companion launch.
[stream-logcat.txt](https://github.com/user-attachments/files/16565437/stream-logcat.txt)

**Comment by victorypoint** [comment] 2024-08-09 18:20
@cagnulein, enjoy your holiday. This stuff can wait!

**Comment by cagnulein** [comment] 2024-08-09 18:35
got the issue, i was trying to remove too much :D anyway from your previous log i already saw that the OCR thing is taking alone more than 1.5sec! that's crazy! so for sure i have to bring this at the minimum pieces possible. and maybe decreasing the color. i just leave you the version fixed. i'm still thinking that the best way will be having access to the usb directly 

https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10324024274/artifacts/1796194526

**Comment by victorypoint** [comment] 2024-08-09 18:48
@cagnulein, if it helps I have working python code that gets a screengrab from the TM and does OCR of speed and inclination using AI.Server (on my Windows PC running PaddleOCR with nVidia card - super fast). The delay is about a second - 2 at most. The delay in this case is the TM as it does a screengrab and transfers the image to my PC over ADB.

**Comment by cagnulein** [comment] 2024-08-09 18:53
i'm trying to put my hands on a nordictrack treadmill or bike broken here in italy to sniff the usb communication. this will be so smooth then. ocr thing is like putting an elephant over a car :) but of course if it's the only way..

**Comment by keatontaylor** [comment] 2024-08-09 19:00
I did try to see if I could get some output from the USB serial interface for the ICON fitness USB device, but didn't have much luck. Suggestions would be great and I might be able to assist with using `adb shell` to see what the serial interface is up to.

**Comment by cagnulein** [comment] 2024-08-09 19:03
@keatontaylor if you can build something like this we will have everything that we need https://hackaday.com/2024/08/03/need-a-usb-sniffer-use-your-pico/

or another way is to decompile very old version of ifit trying to see if the usb code was not obscured.

with @victorypoint i was already able to open the serial communication, now i have to understand the protocol

**Comment by cagnulein** [comment] 2024-08-09 19:31
I just had a blast! Why don't you do the opposite?! I can create a fake ESP32 that expose the HID device that ifit wants and in this way i can get the first request of the ifit and so on! I will bring my esp32 with me on vacation and I will experiment with this!

**Comment by victorypoint** [comment] 2024-08-10 14:21
> got the issue, i was trying to remove too much :D anyway from your previous log i already saw that the OCR thing is taking alone more than 1.5sec! that's crazy! so for sure i have to bring this at the minimum pieces possible. and maybe decreasing the color. i just leave you the version fixed. i'm still thinking that the best way will be having access to the usb directly
> 
> https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/10324024274/artifacts/1796194526

@cagnulein, here is logcat for latest APK. All speed and incline changes received by QZ. Same delays as before.
[stream-logcat.txt](https://github.com/user-attachments/files/16569874/stream-logcat.txt)

**Comment by cagnulein** [comment] 2024-08-10 15:19
Thanks, I will investigate the idea that I had yesterday. Also we should
try paddleocr on android too, to see if it has better performance

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno sab 10 ago 2024 alle 16:22 Al Udell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-08-11 08:42
ok i found that the perfect solution is a raspberry with usb otg. 

i will investigate it when i will come back from the vacation. so exciting!

**Comment by keatontaylor** [comment] 2024-09-19 00:52
Just a heads up, looks like NordicTrack is starting to push the new UI out wider, downgrading back to the old version now says that downgrade is temporary.

**Comment by cagnulein** [comment] 2024-09-19 05:24
Yeah thanks a temporary solution it's already available with OCR, if you
want you can test it too

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 19 set 2024 alle 02:52 Keaton Taylor ***@***.***>
ha scritto:

**Comment by EnglandAngling** [comment] 2024-09-23 12:49
@victorypoint Would you mind letting me know how to install the latest APK when the latest iFIT Beta software is installed...I have an NordicTrack S22i bike. Many thanks.

**Comment by victorypoint** [comment] 2024-09-23 14:00
@EnglandAngling, I do everything over ADB so privileged mode and developer tools ADB debugging definitely have to be enabled. I'm able to activate privileged mode from the iFit beta workout screen. Are you able to do so as well?

**Comment by EnglandAngling** [comment] 2024-09-23 14:04
Hi - I do not know how to activate privileged mode from the iFit beta workout screen - can you let me know how to do that please?

**Comment by victorypoint** [comment] 2024-09-23 15:57
@EnglandAngling, it's exactly the same procedure as before. Do the taps at the top right of the screen. See - https://github.com/cagnulein/QZCompanionNordictrackTreadmill

**Comment by EnglandAngling** [comment] 2024-09-23 15:59
@victorypoint ah ok..I'll give it a try again...I did try but it didn't respond...

**Comment by victorypoint** [comment] 2024-09-23 17:33
@EnglandAngling, I just enabled privileged mode from ifit beta main screen, so it definitely still works.

**Comment by EnglandAngling** [comment] 2024-09-23 18:26
@victorypoint thanks yes, I have managed to do it now...but I can't seem to do anything with the APK - I've downloaded the ZIP file from the web browser that's on the machine, I can view the APK file but not do anything with it...it won't open if I double click on it etc...any ideas?

**Comment by cagnulein** [comment] 2024-09-23 18:29
> @victorypoint thanks yes, I have managed to do it now...but I can't seem to do anything with the APK - I've downloaded the ZIP file from the web browser that's on the machine, I can view the APK file but not do anything with it...it won't open if I double click on it etc...any ideas?

Can't you extract it first on the file manager on the treadmill?

**Comment by EnglandAngling** [comment] 2024-09-23 18:44
I've now managed to install the APK on the bike, thanks. Can you give me a link to the latest software for the QZ for my laptop please, I'm not sure if I have an up-to-date version on my laptop.

**Comment by cagnulein** [comment] 2024-09-23 19:04
Here
https://github.com/cagnulein/qdomyos-zwift/releases/download/nightly/windows-msvc2019-binary-no-python.zip


Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno lun 23 set 2024 alle 20:44 EnglandAngling <
***@***.***> ha scritto:

**Comment by EnglandAngling** [comment] 2024-09-25 06:15
The only metric I'm seeing on QZ on my laptop is "inclination" - all of the other usual metrics such as speed, cadence, resistance remain at zero. I've attached a log. @cagnulein @victorypoint 
[debug-Mon_Sep_23_20_38_23_2024.log](https://github.com/user-attachments/files/17125977/debug-Mon_Sep_23_20_38_23_2024.log)

**Comment by cagnulein** [comment] 2024-09-25 06:41
hi @EnglandAngling i guess i already fixed it! https://github.com/cagnulein/QZCompanionNordictrackTreadmill/actions/runs/11027669224/artifacts/1975357631

**Comment by EnglandAngling** [comment] 2024-09-25 08:32
@cagnulein Thanks, I will give it a try tonight. Is there a way of getting the APK from my laptop to the bike? Earlier in the week I just used the web browser on the bike, but typing in the long URL is not easy...

**Comment by cagnulein** [comment] 2024-09-25 08:33
you can use adb from your laptop, didn't you do before?

**Comment by EnglandAngling** [comment] 2024-09-25 08:38
I was able to do that with the original version of QZ before the Ifit beta update, I just followed the instructions and clicked on what it told me to click on........but I don't know how to use ADB.

**Comment by cagnulein** [comment] 2024-09-25 08:40
@EnglandAngling were you following this one https://github.com/cagnulein/QZCompanionNordictrackTreadmill in the instructions has explained how to push the apk using adb. but you have to replace the apk in the package with the one that I just gave you. If you are unsure, i suggest to use the browser method

**Comment by EnglandAngling** [comment] 2024-09-25 08:43
Ah ok...I can try that. Thanks for your help.

**Comment by EnglandAngling** [comment] 2024-09-26 19:13
OK I've installed everything and now I get resistance reading as well as inclination, but still now speed, cadence or power.....please advise... regards Tim

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by cagnulein** [comment] 2024-09-26 19:15
please share an adb logcat and i will check it!
also at least a debug log from qz
https://github.com/cagnulein/qdomyos-zwift/wiki/How-do-i-get-the-debug-log-in-case-something-doesn't-work%3F

Thanks

Roberto Viola
Software engineer and open source enthusiast
http://robertoviola.cloud



Il giorno gio 26 set 2024 alle 21:14 EnglandAngling <
***@***.***> ha scritto:

**Comment by victorypoint** [comment] 2024-10-05 12:02
@cagnulein, here's details about the iFit beta wolflog:

- location accessible by ADB: /sdcard/android/data/com.ifit.glassos_service/files/.valinorlogs/log.latest.txt 
- TM speed and incline lines are recorded in slightly different format. Examples:

```
Line 2597: 17:14:07.296 INFO SDS Changed KPH from 1.6 kph to 3.21 kph
Line 2600: 17:14:10.429 INFO SDS Changed KPH from 3.21 kph to 4.82 kph
Line 2603: 17:14:12.574 INFO SDS Changed KPH from 4.82 kph to 6.43 kph
Line 2608: 17:14:14.895 INFO SDS Changed KPH from 6.43 kph to 8.04 kph
…
Line 2614: 17:14:24.791 INFO SDS Changed INCLINE from 0.0 % to -3.0 %
Line 2619: 17:14:28.172 INFO SDS Changed INCLINE from -3.0 % to -2.0 %
Line 2624: 17:14:29.490 INFO SDS Changed INCLINE from -2.0 % to -1.0 %
Line 2629: 17:14:30.747 INFO SDS Changed INCLINE from -1.0 % to 0.0 %
```
- Grep is changed to accommodate the new format:

```
adb shell tail -n5000 /sdcard/android/data/com.ifit.glassos_service/files/.valinorlogs/log.latest.txt | grep -a "Changed KPH" | tail -n1 | grep -oP "(?<=to\s)\d+(\.\d+)?(?=\skph)"

adb shell tail -n5000 /sdcard/android/data/com.ifit.glassos_service/files/.valinorlogs/log.latest.txt | grep -a "Changed INCLINE" | tail -n1 | grep -oP "(?<=to\s)[+-]?\d+(\.\d+)?(?=\s%)"
```
Attached is example log and working VBS test code. Hope that helps.
[ifit-beta.zip](https://github.com/user-attachments/files/17266084/ifit-beta.zip)

**Comment by cagnulein** [comment] 2024-10-05 12:09
Awesome, thanks for the info!
I will implement this tomorrow hopefully!

Il giorno sab 5 ott 2024 alle 14:03 Al Udell ***@***.***> ha
scritto:

**Comment by cagnulein** [comment] 2024-10-08 07:52
@keatontaylor @EnglandAngling we have good news, check this https://github.com/cagnulein/QZCompanionNordictrackTreadmill/pull/116

**Comment by EnglandAngling** [comment] 2024-10-08 08:03
OK I will try it again this week thanks.

Tim

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by EnglandAngling** [comment] 2024-10-08 16:37
Hi - still the same for me - only inclination is showing....do I need to adjust some settings in qdomyos-zwift perhaps? I've put the correct IP in there for the bike....anything else need changing or any settings I must use ??

--

Regards Tim
TEL: 01904 400242

England Angling
Unit 17D Malton Road Industrial Estate
Malton Road
York YO32 9TN

web: https://www.englandangling.co.uk
email: ***@***.***

live chat: https://tawk.to/chat/55e80b42ef156c730753a784/default

----------------------------------------

**Comment by cagnulein** [comment] 2024-10-08 16:58
i mean this one https://github.com/cagnulein/QZCompanionNordictrackTreadmill/releases/download/3.5.0/QZCompanionNordictrackTreadmill.apk

@EnglandAngling i don't remember do you have the ifit beta installed?

**Comment by cagnulein** [comment] 2024-10-08 19:35
@EnglandAngling i was checking the log but i can't find any reference of qz

did you run adb while a manual workout was running and qz was showing the inclination?

also please attach it to github directly otherwise its hard to check

**Closed** 2024-11-05 02:18 UTC
Labels: wontfix
